//
// Created by patrick on 8/10/20.
//

#ifndef MNISTMODEL_BASICNETWORKS_H
#define MNISTMODEL_BASICNETWORKS_H


#include "carlsim.h"
#include "../inc/SimMNIST.h"
#include "../inc/Network.h"


#include <string>
#include <vector>
#include <iostream>
#include <cassert>


// arg infile is the input .dat file
// file is generated by genLogoStim.m
// graph and log files are written to output/
// monitor logs written to results/
// weights and kernels have been tuned for 64x64 resolution
void smoothNetwork(const std::string &infile, const std::string &simName);

// arg infile is the input .dat file
// file is generated by genLogoStim.m
// graph and log files are written to output/
// monitor logs written to results/
// weights and kernels have been tuned for 64x64 resolution
void edgeDetNetwork(const std::string &file, const std::string &simName);

#endif //MNISTMODEL_BASICNETWORKS_H
